# Generated by Django 4.0.1 on 2022-03-19 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=50, verbose_name='Уникальный код бронирования')),
                ('booking_description', models.CharField(max_length=200, verbose_name='Примечания')),
                ('booking_date', models.DateTimeField(verbose_name='Дата и время бронирования')),
                ('booking_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец бронирования')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, verbose_name='Название')),
                ('movie_country', models.CharField(max_length=100, verbose_name='Страна')),
                ('movie_year', models.CharField(max_length=10, verbose_name='Год')),
                ('movie_duration', models.IntegerField(verbose_name='Продолжительность')),
                ('movie_description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('movie_genres', models.ManyToManyField(to='main.Genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_is_done', models.BooleanField(verbose_name='Оплата завершена')),
                ('payment_date', models.DateTimeField(auto_now=True, verbose_name='Время платежа')),
                ('payment_info', models.CharField(max_length=100, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_number', models.IntegerField(verbose_name='Номер места')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(verbose_name='Дата и время')),
                ('session_bookings', models.ManyToManyField(to='main.Booking', verbose_name='Бронирования')),
                ('session_movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.movie', verbose_name='Сеанс фильма')),
                ('session_seats', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.seats', verbose_name='Места')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.payment', verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_seats',
            field=models.ManyToManyField(to='main.Seats', verbose_name='Бронируемые места'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.status', verbose_name='Статус'),
        ),
    ]
