# Generated by Django 4.0.1 on 2022-03-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default=0, max_length=50, verbose_name='Уникальный код бронирования'),
        ),
    ]
