# Generated by Django 4.0.1 on 2022-03-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(default='movieImgs/default.jpg', upload_to='movieImgs/', verbose_name='Изображение'),
        ),
    ]
