# Generated by Django 4.0.1 on 2022-03-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_booking_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='session_price',
            field=models.FloatField(default=1, verbose_name='Цена'),
        ),
    ]
