# Generated by Django 4.0.1 on 2022-03-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_moviesession_session_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_description',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Примечания'),
        ),
    ]
