# Generated by Django 4.0.1 on 2022-03-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_booking_booking_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='', max_length=50, verbose_name='Уникальный код бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечания'),
        ),
    ]
